<?php
/**
 * @file
 * gbif_analytics.module
 */

/**
 * Sets up the data directory from which the images will be served.  It is up the site administrator to
 * populate the directory outside of Drupal (e.g. scp the contents in, and set permission etc).
 * See https://github.com/gbif/analytics for the project to produce the images.
 *
 * Implements hook_install().
 */
function gbif_analytics_install() {
	$data_dir = 'public://gbif_analytics';
  $dir_exists = file_prepare_directory($data_dir);
  if (!$dir_exists) {
  	drupal_mkdir($data_dir);
  }
}

/**
 * Implements hook_menu().
 */
function gbif_analytics_menu() {
	$items['analytics'] = array(
		'title' => 'Analytics',
		'description' => 'The page callback can use the arguments provided after the path used as key',
		'page callback' => 'gbif_analytics_url_router',
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
		'menu-name' => 'analytics',
	);
	return $items;
}

/**
 * Implements hook_theme().
 */
function gbif_analytics_theme($existing, $type, $theme, $path) {
	return array(
		'gbif_analytics_home' => array(
			'template' => 'theme/detail',
		),
	);
}

/**
 * This does the routing based on the URL.
 */
function gbif_analytics_url_router($type, $iso2, $subType) {
	$data_sharing = 'This chart shows the total number of records published through GBIF over time, with separate colours for records published from within the country where the species occurred, and those shared by publishers from other countries.';

	# set the images URLs to be served from this machine
	global $base_url;
	$base_images_url = $base_url . "/sites/default/files/gbif_analytics/";

	# assets (e.g. the images) are included in the module, and needed by the template
	$assets_url = $base_url . "/" . drupal_get_path('module', 'gbif_analytics');


	if ($type == 'country' && $subType == 'about'){
		$base_images_url = $base_images_url . 'country' . '/' . $iso2 . '/about/figure' ;
		$data_sharing = 'This chart shows the number of records about biodiversity occurring in '
			. $iso2
			. ', with separate colours for records published from within '
			. $iso2
			. ', and those shared by publishers from other countries.';

	} else if ($type == 'country' && $subType == 'published') {
		$base_images_url = $base_images_url . 'country' . '/' . $iso2 . '/publishedBy/figure' ;
		$data_sharing = 'This chart shows the number of records shared by publishers within '
        . $iso2
        . ' over time, with separate colours for records about species occurring in '
        . $iso2
        . ' and those occurring in other countries.';
	} else {
		$base_images_url = $base_images_url . 'global/figure';
	}

	return theme('gbif_analytics_home', array(
		'img_base_url' => $base_images_url,
		'assets_url' => $assets_url,
		'datasharing_description' => $data_sharing
	));
}

/**
 * Custom libraries for this module to load lightbox, and custom styling.
 *
 * Implements hook_library().
 */
function gbif_analytics_library() {
	$path = drupal_get_path('module', 'gbif_analytics');
	$libraries['lightbox'] = array(
		'title' => 'Lightbox',
		'js' => array(
			$path . '/js/lightbox.min.js' => array(
				'type' => 'file',
				'scope' => 'footer',
				'weight' => 20,
			)
		),
		'css' => array(
			$path . '/css/lightbox.css' => array(
				'type' => 'file',
				'weight' => 20,
			),
		)
	);
	$libraries['analytics'] = array(
		'title' => 'GBIF Analytics custom styling',
		'css' => array(
			$path . '/css/gbif-analytics.css' => array(
				'type' => 'file',
				'weight' => 20,
			),
		)
	);
	return $libraries;
}

/**
 * Load lightbox and custom page styling.
 *
 * Implements hook_preprocess_page().
 */
function gbif_analytics_preprocess_page(&$variables) {

	// load in lightbox CSS and JS
	watchdog('analytics', 'Loading custom libraries for module', array(), WATCHDOG_DEBUG);
	drupal_add_library('gbif_analytics', 'lightbox');
	drupal_add_library('gbif_analytics', 'analytics');

	// Preprocess for the menu tabs.
	// Todo: to fully utilise hook_menu() to potentially avoid working on this here.
	/*
	 * The following snippet is for you to adjust the URL in order to keep the
	 * menu tab active when the country code is in the URL.
	if (isset($variables['page']['menu']['gbif_navigation_analytics'])) {
		foreach ($variables['page']['menu']['gbif_navigation_analytics']['#content'] as $k => $tab) {
			if (gettype($k) == 'integer') {
				$path = explode('/', $tab['#href']);
				$iso2 = arg(1);
				$new_path = $path[0] . '/' . $iso2 . '/' . $path[1];
				$variables['page']['menu']['gbif_navigation_analytics']['#content'][$k]['#href'] = $new_path;
			}
			// If it's not a participant, take the participation menu tab away.
			if (gettype($k) == 'integer' && $tab['#title'] == 'Participation' && count($results) == 0) {
				unset($variables['page']['menu']['gbif_navigation_analytics']['#content'][$k]);
			}
		}
	}
	*/

}

/**
 * Implements hook_page_build().
 */
function gbif_analytics_page_build(&$page) {
	if (isset($page) && arg(0) == 'analytics') {

		// BKO: Please put logic here to determine the title and slogan in the banner area.
		$title = t('Data Trend of GBIF');
		$slogan = t('Some text here when needed.');

		$page['highlighted_title'] = array(
			'name' => $title,
			'description' => $slogan,
		);
	}
}