<?php
/**
 * @file
 * gbif_participant.module
 */

/**
 * Implements hook_menu().
 */
function gbif_participant_menu() {
	$items['country_php'] = array(
		'title' => 'Extra Arguments',
		'description' => 'The page callback can use the arguments provided after the path used as key',
		'page callback' => 'gbif_participant_page_render',
		'access callback' => TRUE,
		'weight' => 10,
	);
	return $items;
}

/**
 * Implements hook_help().
 */
function gbif_participant_help($path, $arg) {
  if ($path == 'admin/help#gbif_participant') {
    return t('Managing and displaying information regarding GBIF Participants.');
  }
}

/**
 * Implements hook_node_info()
 */
function gbif_participant_node_info() {
	$items = array(
		'gbif_participant' => array(
			'name' => t('GBIF Participant'),
			'base' => 'gbif_participant',
			'description' => t('A GBIF Participant profile that contains descriptive information that is shown on the country pages.'),
			'has_title' => TRUE,
			'title_label' => t('GBIF Participant Title'),
			'has_body' => FALSE,
			'body_label' => t('Custom body text'),
			'locked' => TRUE, // Unchangeable from UI.
			'node-preview' => 0,
			'node-options' => array(),
			'node-submitted' => 0,
			'language_content_type' => '1',
			'comment' => array(
				'status' => 0,
				'default-mode' => 0,
				'anonymous' => 2,
				'default-per-page' => 30,
				'form-location' => 0,
				'preview' => 2,
				'subject-field' => 0,
			),
			'menu' => array(
				'options' => array('gbif-menu'),
				'parent' => 'gbif-menu:0',
			),
		),
	);
	return $items;
}

/**
 * Implements hook_form()
 * Provide the title field in the form when editing.
 */
function gbif_participant_form($node, $form_state) {
	$type = node_type_get_type($node);
	$form['title'] = array(
		'#type' => 'textfield',
		'#title' => check_plain($type->title_label),
		'#default_value' => !empty($node->title) ? $node->title : '',
		'#required' => TRUE,
	);
	return $form;
}

/**
 * Implements hook_theme().
 */
function gbif_participant_theme() {
	$path = drupal_get_path('module', 'gbif_participant');
	return array(
		'node__gbif_participant' => array(
			'template' => 'node--gbif_participant',
			'path' => "$path/theme",
		),
	);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function gbif_participant_preprocess_page(&$variables) {
	if (isset($variables)) {
		// For the content type 'gbif_participant', page title is decided by the node information.
		if (isset($variables['node']) && $variables['node']->type == 'gbif_participant') {
			$variables['page']['highlighted_title'] = array(
				'name' => $variables['node']->title,
				'description' => 'draft participant profile',
			);
		}
	}
}

function gbif_participant_preprocess_node(&$variables) {
	if (isset($variables) && $variables['type'] == 'gbif_participant') {

	}
}

function gbif_participant_page_render($iso2, $page) {
	$content = '';
	$content .= 'Country code: ' . $iso2 . '<br/>';
	$content .= 'Page: ' . $page;
	return $content;
}