<?php

$plugin = array(
  'label' => t('Data use'),
  'resource' => 'data_use',
  'name' => 'data_use__0_1',
  'entity_type' => 'node',
  'bundle' => 'data_use',
  'description' => t('Export the data use content type.'),
  'class' => 'GbifRestfulDataUseResource__0_1',
  'authentication_types' => TRUE,
  'authentication_optional' => TRUE,
  'major_version' => 0,
  'minor_version' => 1,
  'pass_through' => TRUE,
);
