<?php
/**
 * @file
 * Code for the GBIF generic feature.
 */

include_once 'gbif_generic.features.inc';

/**
 * Implements hook_page_build().
 */
function gbif_generic_page_build(&$page) {
  // Find the current menu item by path
  $menu_item = menu_link_get_preferred(current_path());
  if (!empty($menu_item)) {
    $parameters = [
      'active_trail' => [$menu_item['plid']],
      'only_active_trail' => FALSE,
      'min_depth' => (int)$menu_item['depth'] + 1,
      'max_depth' => (int)$menu_item['depth'] + 1,
      'conditions' => ['plid' => $menu_item['mlid']],
    ];

    $children = menu_build_tree($menu_item['menu_name'], $parameters);
    $ids = [];
    foreach ($children as $child) {
      $link_path = $child['link']['link_path'];
      $link_exploded = explode('/', $link_path);
      if (isset($link_exploded[0]) && $link_exploded[0] == 'node') {
        if (isset($link_exploded[1])) $ids[] = $link_exploded[1];
      }
    }
    $nodes = node_load_multiple($ids);
    foreach($nodes as $nid => $node) {
      $page['content']['system_main']['nodes'][] = node_view($node); // @todo add langcode when i18n.
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function gbif_generic_form_alter(&$form, &$form_state, $form_id) {
  if (in_array($form_id, array('generic_node_form'))) {
    $form['language']['#required'] = TRUE;
    if (isset($form['language']['#default_value']) && $form['language']['#default_value'] == 'und') {
      $form['language']['#default_value'] = NULL;
    }
    $form['language']['#weight'] = 1;
    $form['field_subtitle']['#weight'] = 1;
    $form['#after_build'][] = 'gbif_generic_node_form_after_build';
  }
}

function gbif_generic_node_form_after_build($form) {
  $form['body']['und']['0']['format']['#access'] = FALSE;
  $form['field_subtitle']['und']['0']['format']['#access'] = FALSE;
  return $form;
}

/**
 * Implements hook_module_implements_alter().
 */
function gbif_generic_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    $group = $implementations['gbif_generic'];
    unset($implementations['gbif_generic']);
    $implementations['gbif_generic'] = $group;
  }
}