<?php
/**
 * @file
 * gbif_resource.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function gbif_resource_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-731qYYP4XLCpEqbjDPEBHvO3Ms6QiFhq'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '731qYYP4XLCpEqbjDPEBHvO3Ms6QiFhq',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bvng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bvng',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Purpose',
    'visibility' => 0,
  );

  $export['facetapi-91UEW2NE4L9KDBz5SLgpe0fiDQZM19OU'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '91UEW2NE4L9KDBz5SLgpe0fiDQZM19OU',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bvng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bvng',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Language',
    'visibility' => 0,
  );

  $export['facetapi-HeCqQSNM4pCh581hH4Aq8jlEIwdyvby7'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'HeCqQSNM4pCh581hH4Aq8jlEIwdyvby7',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bvng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bvng',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Data type',
    'visibility' => 0,
  );

  $export['facetapi-oGePWok3wXOoVeiAT30QHDay08xaMG5a'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'oGePWok3wXOoVeiAT30QHDay08xaMG5a',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bvng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bvng',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Tags',
    'visibility' => 0,
  );

  $export['facetapi-xvKA0HJVTNwngnlCE9lJP4T0CXA1Gn27'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'xvKA0HJVTNwngnlCE9lJP4T0CXA1Gn27',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bvng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bvng',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Resource type',
    'visibility' => 0,
  );

  $export['views--exp-resources_search-page'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '-exp-resources_search-page',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bvng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bvng',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-resources-featured_block'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'resources-featured_block',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'bvng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bvng',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Featured resources',
    'visibility' => 0,
  );

  return $export;
}
