<?php
/**
 * @file
 * Code for the GBIF Bibliography feature.
 */

include_once 'gbif_bibliography.features.inc';

/**
 * Implements hook_menu().
 * @todo Access point for JSON call
 */
function gbif_bibliography_menu() {
  $items = array();
  $items['admin/config/gbif/mendeley/sync'] = array(
    'title' => 'Mendeley sync',
    'description' => t('Synchronise Mendeley citations.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gbif_bibliography_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'gbif_bibliography.admin.inc',
  );
  return $items;
}

/**
 * Sync citations from local JSON to Drupal DB
 */
function gbif_bibliography_sync() {
  // Check if there is a local copy of Mendeley documents.
  $documents_file_loc = file_build_uri('gbif_mendeley/documents.json');
  $file_exists = file_exists(drupal_realpath($documents_file_loc));

  $updated = variable_get('gbif_mendeley_detail_updated');

  if ($file_exists == TRUE && $updated == TRUE) {
    $documents = json_decode(file_get_contents(drupal_realpath($documents_file_loc)));

    foreach ($documents as $doc) {
      

    }
    
    return 'done';
  }
}