<?php

/**
* 
* @ingroup GBIF
*/


/**
* Implements hook_menu().
*
*/
function gfxr_menu() {
	$items['admin/config/gfxr/settings'] = array(
			'title' => 'GBIF Fixer',
			'description' => 'A collection of various fixes needed for the GBIF implementation on Drupal',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('gfxr_form'),
			'access arguments' => array('administer site configuration'),
			'type' => MENU_NORMAL_ITEM,
			'file' => 'gfxr.admin.inc',
			);
	$items['workshop'] = array(
			'title' => 'Sawing/milling machines go here',
			'description' => 'A placeholder',
			'page callback' => 'workshop',
			'access arguments' => array('use the shop'),
			);

	return $items;

}


function gfxr_permission() {
	return array(
		'use the shop' => array(
		'title' => t('Use the workshop tools'),
		'description' => t('Allow users to perform various operations.'),
		),
	);
}

/**
 * Implements hook_token_info().
 */
function gfxr_token_info() {
	global $base_url ;

	$types['gfxr'] = array(
		'name' => t("GBIF Fixer tokens"),
		'description' => t("Tokens for various local fixes"),
	);

	$gfxr['baseurl'] = array(
		'name' => t("$base_url"),
		'description' => t("Emit $base_url to be used inside large text fields"),
	);

	return array(
		'types' => $types,
		'tokens' => array(
		'gfxr' => $gfxr,
	),
	);
}

/**
 * Implements hook_tokens().
 */
function gfxr_tokens($type, $tokens, array $data = array(), array $options = array()) {
  global $user;

	$replacements = array();
  
	if ($type == 'gfxr') {
		foreach ($tokens as $name => $original) {
			switch ($name) {
				case 'cp':
					$replacements[$original] = $GLOBALS['base_url'];
				break;
				case 'dp':
					$replacements[$original] = theme_get_setting( 'vizz2_dataportal_base_url','vizz2' ) ;
				break;
				
			}
		}
	}
  
  return $replacements;
}


/**
 * Implements hook_entity_info_alter().
 *
 * Add an additional display mode
 * so that various custom view(s) can make use of the extra 
 * setting
 */
function gfxr_entity_info_alter(&$entity_info) {
	$entity_info['node']['view modes']['teaser_nt'] = array(
		'label' => t('Teaser_NT'),
		'custom settings' => TRUE,
	);

}

/**
 * Implements hook_node_view().
 *
 * In order for an element to be indexed it has to be rendered first
 * catch it at the rendering stage and clear the content to be indexed.
 *
 */
function gfxr_node_view($node, $view_mode ) {
	// Remove from the index event_ims objects which are older than time of indexing. 
	if ( $node->type == 'event_ims' AND $node->field_start_date['und'][0]['value'] < time() AND $view_mode == 'search_index' ) {
		foreach ( array ('body',
						'field_audience',
						'field_contact',
						'field_venuecountry',
						'field_venue',
						'field_country',
						'field_status',
						'field_resources',
						'field_participants',
						'field_start_date',
						'field_dates',
						'field_city',
						'title') as $field) 
						$node->content[$field]=array(); 
 		$node->title='';
		return $node ; // 5.3 vs 5.4?! 		
	} else if ( $node->type == 'featureddataset' AND $view_mode == 'search_index' ) {
		$node->title = '' ;
		$node->body = array();
		$node->content['body']['#items']['0']['value']='';
		$node->content['body']['#items']['0']['safe_value']='';
		$node->content['body']['0']['#markup']='';
		// $node->content = array();
		return $node ;
	}

}



function workshop() {

}